# Generated by Django 4.2.3 on 2023-07-25 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=50, verbose_name='Nombre del conocimiento')),
                ('respuesta', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='carta.seccioncarta')),
            ],
        ),
    ]
